In [1]:
%matplotlib inline
import os
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math

In [2]:
loan_data = pd.read_csv("loan_data/LoanStats_2017Q3.csv")

/Users/zhejianpeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
loan_data.head(20)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,33000.0,33000.0,33000.0,36 months,7.21%,1022.12,A,A3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,40000.0,40000.0,40000.0,60 months,15.05%,952.65,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,12000.0,12000.0,12000.0,36 months,7.97%,375.88,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,7000.0,7000.0,7000.0,36 months,7.97%,219.26,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,32000.0,32000.0,32000.0,36 months,11.99%,1062.71,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,16000.0,16000.0,16000.0,36 months,7.97%,501.17,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,4000.0,4000.0,4000.0,36 months,9.44%,128.02,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,20000.0,20000.0,20000.0,60 months,10.42%,429.09,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,1200.0,1200.0,1200.0,36 months,23.88%,47.01,E,E2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,24000.0,24000.0,24000.0,60 months,15.05%,571.59,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,35000.0,35000.0,35000.0,36 months,20.00%,1300.73,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,30000.0,30000.0,30000.0,60 months,21.45%,819.22,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,8000.0,8000.0,8000.0,36 months,14.08%,273.74,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,14000.0,14000.0,14000.0,60 months,18.06%,355.97,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,20000.0,20000.0,20000.0,36 months,7.97%,626.46,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,20000.0,20000.0,20000.0,60 months,14.08%,466.20,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,18000.0,18000.0,18000.0,36 months,10.42%,584.37,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,24000.0,24000.0,24000.0,60 months,12.62%,541.42,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,20000.0,20000.0,20000.0,60 months,18.06%,508.53,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,4000.0,4000.0,4000.0,36 months,9.44%,128.02,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
loan_data.index

RangeIndex(start=0, stop=122703, step=1)

Try to delete column which has No Value

In [5]:
for key, value in loan_data.iteritems():
    num_value = 0
    num_nan = 0
    for i in value:
        try:
            if math.isnan(i):
                num_nan +=1
            else:
                num_value +=1
        except TypeError:
            num_value +=1
    if (num_value < 2 ):
        print(key)
        loan_data.drop(key, 1, inplace= True)
    num_value = 0
    num_nan = 0

member_id
url
desc

In [6]:
loan_data.head(20)

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,33000.0,33000.0,33000.0,36 months,7.21%,1022.12,A,A3,Registered Nurse,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,40000.0,40000.0,40000.0,60 months,15.05%,952.65,C,C4,Driver,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,12000.0,12000.0,12000.0,36 months,7.97%,375.88,A,A5,associate,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,7000.0,7000.0,7000.0,36 months,7.97%,219.26,A,A5,CSM,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,32000.0,32000.0,32000.0,36 months,11.99%,1062.71,B,B5,Nurse,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,16000.0,16000.0,16000.0,36 months,7.97%,501.17,A,A5,Senior Investigator,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,4000.0,4000.0,4000.0,36 months,9.44%,128.02,B,B1,Hairdresser,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,20000.0,20000.0,20000.0,60 months,10.42%,429.09,B,B3,IT Project Manager,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1200.0,1200.0,1200.0,36 months,23.88%,47.01,E,E2,Case Manager,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,24000.0,24000.0,24000.0,60 months,15.05%,571.59,C,C4,Senior Vice President Operations,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,35000.0,35000.0,35000.0,36 months,20.00%,1300.73,D,D4,Manager,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,30000.0,30000.0,30000.0,60 months,21.45%,819.22,D,D5,engineer,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,8000.0,8000.0,8000.0,36 months,14.08%,273.74,C,C3,Payroll Admin,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,14000.0,14000.0,14000.0,60 months,18.06%,355.97,D,D2,Staffing Supervisor,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,20000.0,20000.0,20000.0,36 months,7.97%,626.46,A,A5,Test Tech,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,20000.0,20000.0,20000.0,60 months,14.08%,466.20,C,C3,Assistant Director,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,18000.0,18000.0,18000.0,36 months,10.42%,584.37,B,B3,Site Superintendent,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,24000.0,24000.0,24000.0,60 months,12.62%,541.42,C,C1,Body Technician,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,20000.0,20000.0,20000.0,60 months,18.06%,508.53,D,D2,Supervisor,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,4000.0,4000.0,4000.0,36 months,9.44%,128.02,B,B1,NaN,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
loan_data.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,122701.000000,122701.000000,122701.000000,122701.000000,1.227010e+05,122517.000000,122701.000000,122701.000000,62236.000000,18838.000000,...,115.0,115.000000,115.0,115.000000,105.000000,115.000000,115.000000,4.000000,4.000000,4.0
mean,14598.099445,14598.099445,14594.647150,435.640301,7.901073e+04,19.647346,0.355963,0.507192,33.216547,75.795891,...,3.0,217.416957,3.0,2.721739,648.432286,16554.057391,150.949826,5086.045000,65.005000,16.5
std,9613.787458,9613.787458,9611.583306,282.988972,3.219881e+05,20.560868,0.968668,0.803146,21.812893,24.554209,...,0.0,172.081006,0.0,6.840986,513.390853,9421.528419,219.839878,5141.550073,0.005774,3.0
min,1000.000000,1000.000000,1000.000000,30.120000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.0,32.250000,3.0,0.000000,96.750000,3748.760000,0.010000,2188.000000,65.000000,12.0
25%,7000.000000,7000.000000,7000.000000,231.980000,4.550000e+04,12.150000,0.000000,0.000000,15.000000,60.000000,...,3.0,88.175000,3.0,0.000000,266.340000,9800.045000,0.250000,2521.750000,65.000000,16.5
50%,12000.000000,12000.000000,12000.000000,358.980000,6.500000e+04,18.210000,0.000000,0.000000,30.000000,79.000000,...,3.0,156.990000,3.0,0.000000,470.970000,14427.740000,11.660000,2683.000000,65.005000,18.0
75%,20000.000000,20000.000000,20000.000000,582.750000,9.440000e+04,25.010000,0.000000,1.000000,48.000000,94.000000,...,3.0,297.345000,3.0,0.000000,891.240000,23712.345000,237.185000,5247.295000,65.010000,18.0
max,40000.000000,40000.000000,40000.000000,1719.830000,1.100000e+08,999.000000,32.000000,5.000000,178.000000,119.000000,...,3.0,893.050000,3.0,29.000000,2679.150000,40306.410000,1162.260000,12790.180000,65.010000,18.0

Some columns are calculated by Landing Club, so we need to drop them in order to avoid information leakage

In [8]:
loan_data.drop("loan_amnt", 1, inplace= True)

In [9]:
loan_data.drop("funded_amnt", 1, inplace= True)
loan_data.drop("funded_amnt_inv", 1, inplace= True)
loan_data.drop("term", 1, inplace= True)
loan_data.drop("int_rate", 1, inplace= True)
loan_data.drop("installment", 1, inplace= True)
loan_data.drop("grade", 1, inplace= True)
loan_data.drop("sub_grade", 1, inplace= True)

In [10]:
loan_data.drop("title", 1, inplace= True)

for loan_status, this column is set to be y

In [11]:
loan_data.drop("pymnt_plan", 1, inplace= True)

In [12]:
loan_data.drop("application_type", 1, inplace= True)

In [13]:
loan_data.head()

,id,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,zip_code,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,Registered Nurse,< 1 year,MORTGAGE,107000.0,Verified,Sep-2017,Current,debt_consolidation,750xx,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Driver,9 years,MORTGAGE,120000.0,Verified,Sep-2017,Current,debt_consolidation,778xx,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,associate,10+ years,OWN,42000.0,Source Verified,Sep-2017,Current,debt_consolidation,923xx,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,CSM,10+ years,RENT,32000.0,Source Verified,Sep-2017,Current,debt_consolidation,604xx,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Nurse,10+ years,MORTGAGE,155000.0,Source Verified,Sep-2017,Current,credit_card,080xx,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
for key, value in loan_data.iteritems():
    num_value = 0
    num_nan = 0
    for i in value:
        try:
            if math.isnan(i):
                num_nan +=1
            else:
                num_value +=1
        except TypeError:
            None
    if num_nan > 0:
        print(key)
    num_value = 0
    num_nan = 0

id
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
purpose
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_act_il
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit
revol_bal_joint
sec_app_earliest_cr_line
sec_app_inq_last_6mths
sec_app_mort_acc
sec_app_open_acc
sec_app_revol_util
sec_app_open_act_il
sec_app_num_rev_accts
sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med
sec_app_mths_since_last_major_derog
hardship_flag
hardship_type
hardship_reason
hardship_status
deferral_term
hardship_amount
hardship_start_date
hardship_end_date
payment_plan_start_date
hardship_length
hardship_dpd
hardship_loan_status
orig_projected_additional_accrued_interest
hardship_payoff_balance_amount
hardship_last_payment_amount
disbursement_method
debt_settlement_flag
debt_settlement_flag_date
settlement_status
settlement_date
settlement_amount
settlement_percentage
settlement_term

In [15]:
from sklearn import tree

As there are too many rows, we just randomly pick some of them to apply the model

In [16]:
# loan_data = loan_data.sample(frac=0.1, replace=False, weights=None, random_state=0)
loan_data.index

RangeIndex(start=0, stop=122703, step=1)

In [17]:
yval = loan_data['loan_status'];#this column is set to be the "y" in the regression model
loan_status = {}
yval

0                    Current
1                    Current
2                    Current
3                    Current
4                    Current
5                    Current
6                    Current
7                    Current
8                    Current
9                    Current
10                   Current
11                   Current
12                   Current
13                   Current
14                   Current
15                   Current
16                   Current
17                   Current
18                   Current
19                   Current
20                   Current
21                   Current
22                   Current
23                   Current
24                   Current
25                   Current
26                   Current
27                   Current
28                   Current
29                   Current
                 ...
122673               Current
122674               Current
122675               Current
122676           Charged Off
122677               Current
122678    Late (31-120 days)
122679               Current
122680            Fully Paid
122681            Fully Paid
122682               Current
122683               Current
122684               Current
122685               Current
122686               Current
122687            Fully Paid
122688               Current
122689     Late (16-30 days)
122690    Late (31-120 days)
122691               Current
122692               Current
122693       In Grace Period
122694               Current
122695               Current
122696               Current
122697               Current
122698            Fully Paid
122699    Late (31-120 days)
122700               Current
122701                   NaN
122702                   NaN
Name: loan_status, Length: 122703, dtype: object

In [18]:
# Estimate how many different output in Data sets
for i in yval:
    if i in loan_status:
        loan_status[i] +=1
    else:
        loan_status[i] = 1
loan_status

{'Current': 114654,
 'Fully Paid': 5424,
 'Late (31-120 days)': 1114,
 'Late (16-30 days)': 498,
 'In Grace Period': 908,
 'Charged Off': 103,
 nan: 2}

In [49]:
Y = []
counter = 0

In [50]:
for i in yval:
    try:
        if "Late" in i:
            Y.append(1)
        else:
            Y.append(0)
        if (counter % 5000) == 0: # heart beat checking
            print(counter)
    except:
        print(i)
        Y.append(0) 
    counter +=1


'''
for idx, val in enumerate(yval):
    try:
        if "Late" in yval[idx]: # default 1
            yval[idx] = 1;
        else: # good for now label 0
            yval[idx] = 0;#one vs all method to train "current" loan
    except: #nan givn value not default
        yval[idx] = 0
'''

0
5000
10000
15000
20000
25000
30000
35000
40000
45000
50000
55000
60000
65000
70000
75000
80000
85000
90000
95000
100000
105000
110000
115000
120000
nan
nan

'\nfor idx, val in enumerate(yval):\n    try:\n        if "Late" in yval[idx]: # default 1\n            yval[idx] = 1;\n        else: # good for now label 0\n            yval[idx] = 0;#one vs all method to train "current" loan\n    except: #nan givn value not default\n        yval[idx] = 0\n'

In [52]:
# Now I have the correct Output where 1 is default, 0 is havn't default
sum(Y)

1612

If the loan_status contain string 'Late' we consider it default. Thus we late 1 is defualt, 0 is good for now, Delete string data

In [121]:
delete_key = {}
for key, value in loan_data.iteritems():
    num_value = 0
    num_nan = 0
    counter = 0
    for i in value:
        counter +=1
        if isinstance(i, str):
            num_value +=1
    if num_value > 0:
        delete_key[key] = 'input is a string' 
        loan_data.drop(key, 1, inplace= True)
    num_value = 0
    num_nan = 0
    counter = 0

In [122]:
delete_key

{'debt_settlement_flag_date': 'input is a string',
 'id': 'input is a string',
 'settlement_date': 'input is a string',
 'settlement_status': 'input is a string'}

In [174]:
loan_data = loan_data.fillna(0)

In [176]:
loan_data

,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
0,107000.0,19.06,0.0,0.0,0.0,0.0,25.0,0.0,18533.0,52.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,120000.0,31.11,0.0,0.0,0.0,0.0,12.0,0.0,13389.0,26.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,42000.0,27.74,0.0,0.0,0.0,80.0,9.0,1.0,11457.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,32000.0,12.27,0.0,1.0,0.0,89.0,13.0,1.0,7736.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,155000.0,12.35,2.0,1.0,10.0,0.0,20.0,0.0,48309.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,79077.0,15.94,0.0,0.0,38.0,0.0,12.0,0.0,16217.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,52000.0,33.81,0.0,0.0,37.0,0.0,11.0,0.0,10415.0,59.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,120000.0,15.79,0.0,1.0,0.0,0.0,12.0,0.0,10478.0,23.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,30000.0,18.32,0.0,1.0,0.0,0.0,28.0,0.0,2036.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,284000.0,14.53,0.0,0.0,54.0,0.0,9.0,0.0,9378.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,87500.0,3.73,0.0,3.0,0.0,0.0,10.0,0.0,2809.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,125000.0,33.70,1.0,1.0,23.0,0.0,7.0,0.0,80471.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,59926.0,31.50,0.0,2.0,43.0,0.0,35.0,0.0,17673.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,46000.0,31.86,0.0,0.0,0.0,0.0,18.0,0.0,18606.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,96000.0,9.53,0.0,0.0,0.0,0.0,17.0,0.0,29231.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,75000.0,18.72,0.0,0.0,0.0,0.0,17.0,0.0,18779.0,23.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,100000.0,12.04,0.0,0.0,31.0,0.0,7.0,0.0,12757.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,73000.0,9.39,0.0,0.0,46.0,100.0,8.0,1.0,11125.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,80000.0,23.43,0.0,0.0,0.0,0.0,9.0,0.0,10428.0,26.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,32000.0,13.28,0.0,0.0,0.0,47.0,5.0,1.0,4193.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,87788.0,11.33,0.0,0.0,0.0,0.0,3.0,0.0,11034.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,60000.0,6.54,0.0,0.0,52.0,0.0,6.0,0.0,955.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,14470.0,12.70,0.0,1.0,0.0,0.0,9.0,0.0,2947.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,121000.0,19.47,4.0,1.0,16.0,0.0,21.0,0.0,11252.0,35.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,64000.0,22.75,0.0,1.0,37.0,0.0,13.0,0.0,6660.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,29000.0,25.25,0.0,0.0,36.0,0.0,3.0,0.0,2760.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,35000.0,33.71,0.0,0.0,33.0,0.0,5.0,0.0,203.0,31.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,145000.0,17.59,0.0,1.0,45.0,0.0,13.0,0.0,14583.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,38000.0,11.12,0.0,0.0,0.0,0.0,3.0,0.0,1815.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,79000.0,22.22,0.0,0.0,0.0,0.0,6.0,0.0,34416.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122673,52000.0,13.89,0.0,1.0,24.0,0.0,8.0,0.0,17928.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122674,450000.0,1.94,0.0,1.0,49.0,0.0,5.0,0.0,1229.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122675,65000.0,32.13,0.0,0.0,45.0,45.0,30.0,3.0,14425.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122676,68500.0,31.83,0.0,0.0,58.0,0.0,11.0,0.0,23908.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122677,90000.0,18.16,0.0,2.0,0.0,79.0,11.0,1.0,12919.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122678,133000.0,31.07,0.0,0.0,0.0,85.0,27.0,1.0,42911.0,48.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122679,37000.0,32.44,0.0,1.0,0.0,0.0,5.0,0.0,3231.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122680,98000.0,32.08,0.0,0.0,34.0,0.0,24.0,0.0,30309.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122681,88000.0,18.63,0.0,0.0,44.0,0.0,10.0,0.0,37031.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122682,60000.0,12.66,0.0,2.0,0.0,34.0,4.0,1.0,3098.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122683,70000.0,17.56,0.0,1.0,35.0,0.0,12.0,0.0,23922.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122684,90000.0,8.30,0.0,1.0,29.0,0.0,13.0,0.0,2495.0,26.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122685,39500.0,30.08,0.0,0.0,0.0,0.0,9.0,0.0,13903.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122686,35000.0,30.62,1.0,0.0,13.0,0.0,10.0,0.0,4881.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122687,126999.0,32.41,0.0,1.0,38.0,0.0,29.0,0.0,42358.0,62.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122688,50000.0,21.65,3.0,3.0,21.0,0.0,10.0,0.0,2993.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122689,65000.0,20.96,0.0,0.0,39.0,34.0,26.0,1.0,3156.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122690,55000.0,19.31,0.0,1.0,59.0,0.0,16.0,0.0,8151.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122691,66000.0,2.44,0.0,1.0,0.0,0.0,3.0,0.0,4801.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122692,43000.0,12.62,1.0,0.0,20.0,0.0,8.0,0.0,15854.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122693,60051.0,19.52,0.0,1.0,34.0,70.0,13.0,1.0,993.0,50.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122694,80000.0,34.11,0.0,3.0,67.0,0.0,9.0,0.0,17147.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122695,87000.0,13.45,0.0,0.0,66.0,79.0,13.0,1.0,9891.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122696,40000.0,34.29,0.0,1.0,75.0,0.0,14.0,0.0,12788.0,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122697,52000.0,23.49,0.0,1.0,0.0,0.0,18.0,0.0,8083.0,34.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122698,75000.0,25.44,0.0,1.0,0.0,0.0,9.0,0.0,13396.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122699,105000.0,14.86,0.0,2.0,35.0,0.0,9.0,0.0,4162.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122700,45000.0,25.20,0.0,2.0,0.0,0.0,12.0,0.0,5556.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122701,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122702,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [177]:
Y = np.array(Y)
X = np.array(loan_data)

In [178]:
def is_not_number(s):
    try:
        float(s)
        return False
    except ValueError:
        return True

In [179]:
clf = tree.DecisionTreeClassifier()

In [180]:
clf = clf.fit(X, Y)

In [202]:
a = np.zeros(100)
clf.predict([X[60]])

array([1])

In [41]:
a = np.zeros(3)
test= ["Late","Late","Note"]
for i in test:
    try:
        print("Late" in i)
        if "Late" in i:
            a[0] = 5
            print(i)
        else:
            print("hi")
            i = 0
        if (counter % 5000) == 0: # heart beat checking
            print(counter)
        counter +=1
    except:
        None

True
Late
True
Late
False
hi

In [199]:
for idx, i in enumerate(Y):
    if i == 1:
        print(idx)

60
158
685
939
1011
1019
1061
1078
1110
1148
1279
1898
1935
1945
1946
2184
2281
2577
2580
2655
2671
2707
2910
2977
3155
3214
3383
3716
4003
4288
4431
4436
4444
4583
4973
5037
5122
5163
5221
5234
5241
5382
5473
5745
5810
5876
6025
6281
6325
7374
7469
7918
8120
8282
8633
8700
8878
9133
9391
9397
9603
9638
9682
9743
9748
9816
9849
10016
10044
10323
10463
11019
11109
11215
11366
11504
11595
11906
12164
12237
12544
13148
13311
13547
13603
13840
13895
13971
14511
14918
14961
14992
15070
15330
15393
15577
15627
15631
15763
15995
16005
16041
16233
16495
16619
16724
17289
17408
17428
17474
17593
17644
17699
17703
17733
17827
18031
18292
18324
18360
18791
18866
18979
19035
19044
19324
19383
19579
19711
19837
20350
20659
20710
20783
20992
21046
21129
21135
21136
21384
21539
21807
21868
22000
22116
22380
22400
22403
22472
22488
22593
22743
22860
22908
22964
23213
23328
23479
23480
23592
23639
24126
24129
24418
24501
24625
24880
25052
25172
25191
25211
25304
25456
25457
25482
25894
25958
26169
26249
26357
26393
26737
26960
27017
27021
27279
27320
27367
27442
27575
27654
27726
27727
27748
27763
27773
27833
28026
28072
28075
28227
28314
28378
28501
28619
28844
28890
28947
28962
29052
29076
29137
29296
29384
29472
29792
29852
30065
30124
30199
30338
30412
30981
30994
31112
31263
31537
31654
32041
32248
32299
32313
32346
32501
32516
32531
32537
32766
32870
32903
32944
33048
33132
33143
33195
33254
33456
33486
33514
33549
33821
34032
34073
34128
34227
34345
34507
34770
34956
34976
35125
35168
35183
35249
35284
35392
35463
35564
35756
35928
35969
36040
36061
36097
36137
36222
36247
36381
36427
36451
36499
36578
36755
37110
37253
37332
37428
37724
37842
37922
37954
37958
37995
38118
38138
38204
38335
38475
38586
38637
38766
38885
38913
39034
39093
39098
39117
39210
39225
39241
39518
39650
40065
40078
40118
40186
40302
40358
40470
40519
40811
40869
40912
41032
41050
41057
41066
41125
41345
41620
41672
41737
41849
41887
42005
42056
42136
42159
42186
42269
42331
42366
42399
42525
42839
42854
42893
43202
43218
43304
43373
43411
43431
43510
43563
43567
43609
43658
43971
43988
44054
44158
44174
44213
44347
44379
44444
44560
44588
44627
44663
44686
44727
44785
44795
44894
44897
44986
45034
45059
45225
45256
45266
45407
45427
45644
45680
45693
45895
46012
46241
46308
46376
46411
46466
46546
46738
46830
46834
46964
47015
47075
47081
47114
47221
47434
47549
47703
47712
47713
47918
48108
48141
48276
48333
48343
48369
48500
48503
48615
48637
48653
48918
48989
49046
49111
49202
49237
49273
49338
49369
49384
49487
49635
49661
49757
49795
49903
50221
50292
50343
50439
50532
50705
50760
50793
50872
50973
50975
51079
51139
51189
51306
51702
51709
51786
51889
51983
52103
52127
52260
52387
52549
52585
52653
52688
52735
52890
53013
53050
53177
53461
53603
53621
54259
54312
54478
54486
54714
54766
54791
55118
55490
55581
55617
55657
55764
56027
56379
56739
56768
56930
56977
57113
57227
57411
57592
57702
57733
57753
57829
57848
57864
57929
58235
58270
58338
58484
58570
58619
58776
58844
58887
58929
59338
59351
59400
59421
59472
59591
59685
59974
60006
60238
60291
60436
60448
60465
60505
60638
60654
60727
60843
60864
60875
60916
61005
61172
61220
61235
61356
61369
61404
61431
61447
61498
61507
61515
61518
61728
61746
61824
61854
62058
62099
62230
62344
62355
62423
62456
62485
62581
62590
62624
62717
62775
62805
62871
62997
63027
63051
63164
63170
63267
63278
63298
63335
63367
63433
63471
63541
63562
63936
63954
63992
64005
64068
64076
64176
64314
64336
64406
64410
64417
64517
64772
64852
64895
65005
65148
65228
65339
65349
65358
65368
65438
65648
65658
65755
65803
65932
65943
66098
66127
66137
66149
66226
66260
66269
66346
66451
66504
66628
66639
66788
66941
66958
67038
67275
67388
67418
67423
67424
67452
67469
67507
67527
67572
67667
67729
67763
67764
67830
67855
67879
67992
68001
68064
68103
68157
68193
68198
68304
68329
68356
68383
68430
68447
68531
68630
68773
68777
68780
68877
68949
68962
69047
69056
69110
69155
69260
69275
69276
69333
69412
69422
69510
69517
69610
69799
69822
69834
69838
69899
69964
70010
70013
70117
70202
70369
70707
70837
70891
70928
70940
71025
71060
71207
71225
71243
71246
71253
71360
71366
71409
71423
71443
71468
71486
71709
71773
71778
71779
71820
71858
71891
71900
71940
71947
72306
72386
72409
72648
72738
72744
72753
72802
72842
72875
73010
73121
73170
73229
73462
73603
73672
73725
73799
73818
73831
73840
73925
73970
73991
74004
74058
74117
74174
74238
74239
74249
74255
74268
74276
74286
74306
74369
74396
74418
74479
74489
74556
74564
74652
74900
74978
75010
75104
75121
75233
75265
75272
75283
75438
75487
75524
75542
75570
75600
75718
75900
75911
75964
75987
76030
76113
76201
76209
76235
76304
76305
76370
76374
76502
76556
76675
76769
76775
76826
76857
76863
76865
77010
77193
77197
77244
77252
77289
77376
77415
77458
77496
77557
77590
77707
77785
77824
78096
78110
78123
78154
78205
78233
78237
78247
78273
78305
78376
78418
78448
78481
78557
78677
78718
78734
78811
78910
78919
78941
79015
79037
79043
79325
79385
79453
79543
79646
79789
79865
79895
79906
79930
80018
80100
80205
80234
80363
80407
80567
80646
80653
80706
80745
80778
80803
80818
80977
81007
81013
81112
81119
81126
81239
81371
81392
81423
81517
81537
81584
81627
81648
81655
81673
81705
81735
81769
81772
81785
81790
81838
81905
82212
82383
82405
82524
82542
82594
82606
82690
82984
83115
83135
83292
83349
83561
83566
83631
83655
83684
83700
83806
83814
83817
83836
83903
83905
83987
83996
84020
84055
84107
84142
84316
84398
84413
84419
84524
84569
84641
84661
84727
84758
84772
84984
84986
85017
85087
85159
85370
85389
85494
85610
85644
85751
85909
85983
86146
86155
86253
86283
86308
86386
86424
86425
86515
86527
86588
86637
86667
86694
86720
86786
86815
86899
86907
86919
86943
86965
86968
87051
87098
87169
87199
87356
87452
87662
87704
87750
87953
88061
88254
88398
88670
88686
88766
88889
88939
89073
89083
89095
89110
89113
89120
89151
89185
89229
89369
89441
89509
89523
89562
89625
89626
89653
89674
89961
89962
90085
90176
90185
90294
90312
90489
90499
90533
90572
90657
90658
90725
90741
90762
90778
90825
90855
90950
90954
91100
91301
91359
91467
91737
91768
92006
92007
92091
92235
92321
92426
92446
92475
92577
92599
92645
92655
92744
92853
93080
93160
93268
93456
93506
93592
93593
93626
93628
93632
93671
93705
93718
93763
93795
93843
93851
93947
94335
94544
94584
94718
94738
94759
94867
94879
94911
94970
95015
95025
95172
95240
95382
95408
95508
95556
95711
95729
95752
95879
95931
96142
96272
96296
96379
96434
96598
96621
96631
96722
96726
96793
96876
96975
97096
97126
97139
97265
97272
97457
97632
97785
97838
97842
97916
97966
98171
98240
98265
98293
98584
98595
98662
98767
98793
98833
98871
98892
98916
99034
99156
99404
99427
99459
99547
99598
99673
99819
99823
99883
100020
100060
100099
100204
100264
100596
100602
100660
100673
100674
100710
100723
100766
100993
101033
101057
101061
101160
101340
101374
101445
101776
101820
101896
101910
101917
102036
102062
102064
102266
102288
102553
102555
102716
102724
102798
102925
102926
103083
103113
103161
103325
103602
103632
103636
103740
103839
103843
103863
103933
104126
104193
104253
104357
104358
104373
104463
104490
104504
104529
104563
104581
104586
104791
104797
104803
104837
104845
104878
104945
104947
104952
104978
105040
105074
105082
105115
105159
105190
105292
105323
105343
105355
105432
105669
105679
105707
105746
105756
105785
105946
106027
106043
106066
106091
106137
106153
106170
106287
106296
106361
106383
106384
106385
106412
106451
106515
106608
106699
106704
106742
106813
106900
106909
106924
106980
107216
107296
107366
107378
107511
107695
107858
107942
107943
107966
107979
108002
108031
108140
108237
108302
108356
108389
108481
108499
108506
108525
108531
108569
108650
108668
108671
108694
108708
108762
108795
108834
108901
108904
109070
109071
109137
109299
109377
109433
109496
109737
109758
109811
109936
109937
110153
110186
110218
110269
110272
110280
110282
110309
110406
110468
110480
110487
110529
110592
110790
110891
110976
110981
111020
111046
111149
111178
111311
111361
111412
111679
111715
111746
111760
111772
111799
111966
111988
112142
112164
112205
112214
112232
112263
112279
112343
112422
112440
112452
112494
112529
112543
112545
112553
112616
112648
112754
112773
112776
112830
112932
113026
113033
113216
113286
113294
113350
113415
113427
113443
113471
113489
113497
113513
113540
113547
113551
113678
113684
113705
113750
113760
113907
113926
113937
114048
114060
114077
114101
114140
114143
114253
114293
114378
114393
114407
114454
114461
114474
114537
114551
114661
114673
114690
114706
114738
114826
114831
114848
114868
114888
114899
114918
115051
115070
115072
115095
115122
115143
115161
115178
115213
115242
115244
115304
115317
115547
115549
115581
115606
115677
115678
115706
115712
115713
115760
115825
115984
116006
116129
116137
116204
116208
116212
116242
116244
116255
116265
116293
116387
116395
116419
116435
116492
116503
116686
116706
116738
116757
116802
116834
116896
116988
117021
117106
117249
117257
117301
117355
117453
117525
117528
117532
117536
117549
117717
117731
117774
117795
117893
117923
117997
118042
118062
118108
118115
118170
118224
118253
118266
118274
118280
118286
118329
118333
118357
118365
118397
118475
118514
118701
118763
118849
118854
118913
118924
118968
118995
119036
119161
119202
119331
119345
119418
119473
119554
119577
119580
119590
119666
119683
119706
119806
119902
119929
119967
120015
120027
120071
120087
120147
120166
120171
120263
120297
120316
120353
120380
120487
120554
120575
120665
120671
120725
120748
120781
120796
120841
120882
120916
120944
120963
120981
120982
120986
120997
120998
121016
121027
121032
121039
121042
121045
121086
121131
121168
121199
121250
121300
121317
121344
121397
121399
121405
121428
121448
121455
121467
121501
121528
121547
121551
121567
121575
121607
121654
121719
121723
121731
121755
121808
121851
121853
121922
122038
122127
122247
122269
122276
122300
122326
122332
122350
122372
122374
122377
122449
122490
122503
122506
122516
122608
122622
122643
122663
122678
122689
122690
122699

1

In [201]:
import

array([  5.30000000e+04,   2.12000000e+01,   0.00000000e+00,
         4.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         5.00000000e+00,   0.00000000e+00,   4.17900000e+03,
         9.00000000e+00,   1.08352200e+04,   1.08352200e+04,
         4.35340000e+02,   4.35340000e+02,   1.89780000e+02,
         2.45560000e+02,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   4.73120000e+02,   0.00000000e+00,
         3.80000000e+01,   1.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         4.61870000e+04,   3.00000000e+00,   1.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   3.00000000e+00,
         4.20080000e+04,   1.00000000e+02,   3.00000000e+00,
         3.00000000e+00,   2.25900000e+03,   7.10000000e+01,
         5.89000000e+03,   0.00000000e+00,   0.00000000e+00,
         4.00000000e+00,   4.00000000e+00,   9.23700000e+03,
         2.40000000e+03,   8.20000000e+01,   0.00000000e+00,
         0.00000000e+00,   3.00000000e+00,   1.50000000e+02,
         3.00000000e+00,   3.00000000e+00,   0.00000000e+00,
         3.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   2.00000000e+00,
         4.00000000e+00,   2.00000000e+00,   3.00000000e+00,
         1.00000000e+00,   4.00000000e+00,   6.00000000e+00,
         4.00000000e+00,   5.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   4.00000000e+00,
         7.80000000e+01,   1.00000000e+02,   0.00000000e+00,
         0.00000000e+00,   4.77190000e+04,   4.61870000e+04,
         4.80000000e+03,   4.18290000e+04,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00])

In [213]:
tree.export_graphviz(clf, out_file='tree.dot')

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.